services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 5s
      timeout: 3s
      retries: 10

  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  event-api:
    build:
      context: ./event-api
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      EVENT_TOPIC: events
      DLQ_TOPIC: events_dlq
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_started
    restart: on-failure

  event-consumer:
    build:
      context: ./event-consumer
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      EVENT_TOPIC: events
      POSTGRES_HOST: db
      POSTGRES_DB: events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_started
    restart: on-failure