apiVersion: v1
kind: Service
metadata:
  name: event-api
spec:
  type: NodePort    # Use ClusterIP for EKS/internal; NodePort for local testing
  selector:
    app: event-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080   # For minikube/kind; omit for EKS/production
