apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  containers:
    - name: kafka
      image: obsidiandynamics/kafka
      ports:
        - containerPort: 9092
        - containerPort: 2181
      env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: BROKER_ID
          value: "1"
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: zookeeper
      port: 2181
      targetPort: 2181
  type: ClusterIP
