apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - port: 2181
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  containers:
    - name: zookeeper
      image: wurstmeister/zookeeper
      ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  containers:
    - name: kafka
      image: wurstmeister/kafka
      env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_PORT
          value: "9092"                # <---- THIS LINE IS CRITICAL
      ports:
        - containerPort: 9092


